import {
  faHome,
  faUsers,
  faCubes,
  faChartLine,
  faCogs,
  faEdit,
  faCheck,
  faExclamation,
  faTrash,
  faArrowRight,
  faArrowLeft,
  faBars,
  faSignInAlt,
  faSignOutAlt,
  faShoppingCart,
  faClipboardList,
  faDollarSign,
  faArchive,
  faPlus,
  faChevronDown,
  faChevronUp
} from '@fortawesome/free-solid-svg-icons';

export const icons = {
  home: faHome,
  users: faUsers,
  products: faCubes,
  stats: faChartLine,
  config: faCogs,
  edit: faEdit,
  check: faCheck,
  exclamation: faExclamation,
  trash: faTrash,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  bars: faBars,
  signOut: faSignOutAlt,
  signIn: faSignInAlt,
  ventas: faShoppingCart,
  movementList: faClipboardList,
  archive: faArchive,
  expenses: faDollarSign,
  plus: faPlus,
  chevDown: faChevronDown,
  chevUp: faChevronUp
};
