import {
    faHome,
    faUsers,
    faCubes,
    faChartLine,
    faCogs,
    faEdit,
    faCheck,
    faExclamation,
    faTrash,
    faSave,
    faArrowRight,
    faArrowLeft,
    faBars,
    faSignInAlt,
    faSignOutAlt,
    faShoppingCart,
    faClipboardList,
    faDollarSign,
    faArchive,
    faPlus,
    faChevronDown,
    faChevronUp,
    faTimes,
    faLock,
    faLockOpen,
    faEye,
    faFilter,
    faSearch,
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
    home: faHome,
    users: faUsers,
    products: faCubes,
    stats: faChartLine,
    config: faCogs,
    edit: faEdit,
    check: faCheck,
    exclamation: faExclamation,
    trash: faTrash,
    arrowLeft: faArrowLeft,
    arrowRight: faArrowRight,
    bars: faBars,
    signOut: faSignOutAlt,
    signIn: faSignInAlt,
    ventas: faShoppingCart,
    movementList: faClipboardList,
    archive: faArchive,
    expenses: faDollarSign,
    plus: faPlus,
    chevDown: faChevronDown,
    chevUp: faChevronUp,
    save: faSave,
    times: faTimes,
    lockOpen: faLockOpen,
    lock: faLock,
    eye: faEye,
    filter: faFilter,
    search: faSearch,
}
